### ISSUE TITLE
Temas sin contenido 

### ISSUE THREAD

**Issue by alexfuser** [mayela/manual-curso-codeandomx#4]

**Comment by mayela** [comment]
Capítulo 1 Terminar los puntos: Problemas comunes, Soluciones, Hacer la programación fácil para ti y fácil para los demás, como se convierte uno en programador(tips, clean code, buenas prácticas).
Capítulo 3: Leer-Buscar-Preguntar(construye tu conocimiento) post relacionado en issue #2.
Capítulo 6: Visual Code, agregar atajos de teclado.
Capítulo 9: Agregar más imágenes, ejemplos de la consola.
